project:
  type: book
  output-dir: docs

book:
  title: "Single- and Multi-Agent Decision Theory"
  author: 
    - name: "Aditya Mahajan"
      url: "https://cim.mcgill.ca/~adityam"
      affiliation: "McGill University"
      affiliation-url: "https://www.mcgill.ca/ece"
  date: today
  description: "Course notes on ECES 506 (Stochastic Control and Decision Theory} and ECSE 508 (Multi-agent systems)"
  site-url: "https://adityam.github.io/course-notes/"
  sidebar:
    collapse-level: 1
    pinned: true
  chapters:
    - index.qmd
    - part: "Static Stochastic Optimization"
      chapters:
        - notes/stochastic-optimization/intro.qmd
        - notes/stochastic-optimization/newsvendor.qmd
    - part: "Markov decision processes"
      chapters:
        - notes/mdps/intro.qmd
        - notes/mdps/gambling.qmd
        - notes/mdps/inventory-management.qmd
        - notes/mdps/monotone-mdps.qmd
        - notes/mdps/power-delay-tradeoff.qmd
        - notes/mdps/inf-horizon.qmd
        - notes/mdps/mdp-algorithms.qmd
        - notes/mdps/inventory-management-revisited.qmd
        - notes/mdps/mobile-edge-computing.qmd
        - notes/mdps/lipschitz-mdps.qmd
    - part: "Approximate Dynamic Programming"
    - part: "Risk sensitive Markov decision processes"
    - part: "Partially observable Markov decision processes"
    - part: "Reinforcement Learning"
    - part: "Linear Quadratic Control"
    - part: "Strategic Games"
    - part: "Dynamic or Extensive Form Games"
    - part: "Probability Appendix"
    - part: "Linear Algebra Appendix"
      chapters:
        - linear-algebra/svd.qmd
        - linear-algebra/rkhs.qmd
    - notes/references.qmd
    - part: "506 Assignments"
      chapters:
        - 506/01.qmd

bibliography: references.bib
csl: _extensions/csl/acm-siggraph.csl

format:
  html:
    theme: 
      - yeti
      - static/css/style.scss
    include-in-header: 
      - static/html/mathjax.html
      - static/html/clicky.html
    reference-location: margin
      #    citation-location: margin
    filters:
      - nutshell



