project:
  type: book
  output-dir: docs

book:
  title: "Single- and Multi-Agent Decision Theory"
  author: 
    - name: "Aditya Mahajan"
      url: "https://cim.mcgill.ca/~adityam"
      affiliation: "McGill University"
      affiliation-url: "https://www.mcgill.ca/ece"
  date: today
  description: "Course notes on ECES 506 (Stochastic Control and Decision Theory} and ECSE 508 (Multi-agent systems)"
  site-url: "https://adityam.github.io/course-notes/"
  sidebar:
    collapse-level: 2
    pinned: true
  chapters:
    - index.qmd
    - part: "Static Stochastic Optimization"
      chapters:
        - notes/stochastic-optimization/intro.qmd
        - notes/stochastic-optimization/newsvendor.qmd
    - part: "Markov decision processes"
      chapters:
        - notes/mdps/intro.qmd
        - notes/mdps/gambling.qmd
    - notes/references.qmd
    - part: "506 Assignments"
      chapters:
        - 506/01.qmd

bibliography: notes/references.bib
csl: _extensions/csl/acm-siggraph.csl

format:
  html:
    theme: 
      - yeti
      - static/css/style.scss
    include-in-header: static/html/mathjax.html
    reference-location: margin
      #    citation-location: margin



