project:
  type: website
  output-dir: docs
  render: 
    - index.qmd

website:
  title: Course Notes
  navbar:
    background: primary
    pinned: false
    left:
    - href: index.html
      text: Home
    - href: stochastic-control/index.html
      text: Stochastic Control
    - href: multi-agent-systems/index.html
      text: Multi-Agent Systems
format:
  html:
    theme:
    - yeti
    - custom.scss
    toc: true
