project:
  type: book
  output-dir: docs

book:
  title: "Single- and Multi-Agent Decision Theory"
  author: 
    - name: "Aditya Mahajan"
      url: "https://cim.mcgill.ca/~adityam"
      affiliation: "McGill University"
      affiliation-url: "https://www.mcgill.ca/ece"
  date: "4/22/2023"
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Static Stochastic Optimization"
      chapters:
        - notes/stochastic-optimization/intro.qmd
        - notes/stochastic-optimization/newsvendor.qmd
    - notes/references.qmd
    - part: "506 Assignments"
      chapters:
        - 506/01.qmd

bibliography: notes/references.bib
csl: _extensions/csl/acm-siggraph.csl

format:
  html:
    theme: 
      - cosmo
      - static/css/style.scss
    include-in-header: static/html/mathjax.html
    reference-location: margin
      #    citation-location: margin



