project:
  type: book
  output-dir: ../docs/stochastic-control
  resources: 'www/geogebra/*.ggb'

book:
  title: Course Notes
  author: 
    - name: Aditya Mahajan
      url: "https://cim.mcgill.ca/~adityam"
      affiliation: McGill University
      affiliation-url: "https://www.mcgill.ca/ece"
  description: "ECES 506 (Stochastic Control and Decision Theory)"
  site-url: "https://adityam.github.io/course-notes/"

  navbar:
    background: dark
    title: false
    pinned: false
    left:
      # - href: ../index.html
      #   text: Home
    - href: ../stochastic-control/index.html
      text: Stochastic Control
    - href: ../multi-agent-systems/index.html
      text: Multi-Agent Systems

  sidebar:
    background: light
    collapse-level: 2
    pinned: false
    style : docked

  chapters:
    - index.qmd
    - part: "Static Stochastic Optimization"
      chapters:
        - stochastic-optimization/intro.qmd
        - stochastic-optimization/newsvendor.qmd
    - part: "Markov decision processes"
      chapters:
        - mdps/intro.qmd
        - mdps/gambling.qmd
        - mdps/inventory-management.qmd
        - mdps/monotone-mdps.qmd
        - mdps/power-delay-tradeoff.qmd
        - mdps/inf-horizon.qmd
        - mdps/mdp-algorithms.qmd
        - mdps/inventory-management-revisited.qmd
        - mdps/mobile-edge-computing.qmd
        - mdps/computational-complexity-vi.qmd
        - mdps/linear-programming.qmd
        - mdps/lipschitz-mdps.qmd
    - part: "Approximate Dynamic Programming"
      # chapters:
      #   - approx-mdps/regularized-mdps.qmd
    - part: "Risk sensitive Markov decision processes"
    - part: "Partially observable Markov decision processes"
      chapters:
        - pomdps/intro.qmd
    - part: "Reinforcement Learning"
    - part: "Linear Quadratic Control"
    - part: "Probability Appendix"
      chapters:
        - probability/sub-gaussian.qmd

    - part: "Linear Algebra Appendix"
      chapters:
        - linear-algebra/postive-definite-matrix.qmd
        - linear-algebra/svd.qmd
        - linear-algebra/rkhs.qmd
    - references.qmd
    - part: "Assignments"
      chapters:
        - assignments/01.qmd

bibliography: ../references.bib
csl: ../_extensions/csl/acm-siggraph.csl

format:
  html:
    theme: 
      - yeti
      - ../static/css/style.scss
    include-in-header: 
      - ../static/html/mathjax.html
      - ../static/html/clicky.html
    reference-location: margin
      #    citation-location: margin
    filters:
      - ../_extensions/schochastics/nutshell/nutshell.lua
    published-title: Updated
    date: last-modified



